config/routes.rb
Rails.application.routes.draw do
	
	devise_for :users
	
	devise_scope :user do
		get '/admin' => 'devise/sessions#new'
	end
	
	root 'welcome#index'

	get 'user_root' => 'welcome#admin'


	resources :movies, :auditoriums, :orders, :showtimes

end

app/models/auditorium.rb
class Auditorium < ApplicationRecord
	has_many :showtimes, dependent: :destroy
end

app/controllers/auditoriums_controller.rb
class AuditoriumsController < ApplicationController
	before_action :user_admin
	before_action :set_auditorium, only: [:show, :edit, :update, :destroy]
	before_action :now_playing, only: [:index]

	def index
		@auditoriums = Auditorium.all
	end

	def show
	end

	def new
		@auditorium = Auditorium.new
	end

	def edit
	end

	def create
		@auditorium = Auditorium.new(auditorium_params)

		respond_to do |format|
			if @auditorium.save
				format.html { redirect_to :controller => 'welcome', :action => 'admin', notice: 'Auditorium was successfully created.' }
				format.json { render :show, status: :created, location: @auditorium }
			else
				format.html { render :new }
				format.json { render json: @auditorium.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		respond_to do |format|
			if @auditorium.update(auditorium_params)
				format.html { redirect_to :controller => 'welcome', :action => 'admin', notice: 'Auditorium was successfully updated.' }
				format.json { render :show, status: :ok, location: @auditorium }
			else
				format.html { render :edit }
				format.json { render json: @auditorium.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@auditorium.destroy
		respond_to do |format|
			format.html { redirect_to :controller => 'welcome', :action => 'admin', notice: 'Auditorium was removed successfully.' }
			format.json { head :no_content }
		end
	end

	private

    def set_auditorium
      @auditorium = Auditorium.find(params[:id])
	end
	
	def auditorium_params
		params.require(:auditorium).permit(:name, :capacity)
	end

	def now_playing
		movies = Movie.where(now_playing: true)
		@movies = ["None"]
		movies.each do |movie|
			@movies << movie.title
		end
	end
end

app/helpers/auditoriums_helper.rb
module AuditoriumsHelper
end

app/views/auditoriums/_form.html.erb
<% if @auditorium.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@auditorium.errors.count, "error") %> prohibited this auditorium from being saved:</h2>

    <ul>
    <% @auditorium.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :capacity %><br>
  <%= f.number_field :capacity, min: 0 %>
</div>  
<div class="actions">
  <%= f.submit %>
</div>

app/views/auditoriums/edit.html.erb
<h1>Edit Auditorium</h1>

	<%= form_for @auditorium, url: auditorium_path(@auditorium), html: {method: :put} do |f| %>

		<%= render 'form', f: f  %>

	<% end %>


<%= link_to 'Show', @auditorium %>
<%= link_to 'Delete', @auditorium, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', user_root_path %>

app/views/auditoriums/new.html.erb
<h1>New Auditorium</h1>
<%= form_for @auditorium, url: auditoriums_path, html: {method: :post} do |f| %>
	<%= render 'form', f: f %>
<% end %>

<%= link_to 'Back', user_root_path %>

app/views/auditoriums/show.html.erb
<h1><%= @auditorium.name %></h1>

<h2><%= @auditorium.capacity %></h2>
<h2><!-- Auditorium now playing logic --></h2>
<h2><%= link_to 'Add Showtimes', new_showtime_path(:auditorium => @auditorium.id) %></h2>

<%= link_to 'Edit', edit_auditorium_path %>
<%= link_to 'Delete', @auditorium, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', user_root_path %>