config/routes.rb
Rails.application.routes.draw do
	
	devise_for :users
	
	devise_scope :user do
		get '/admin' => 'devise/sessions#new'
	end
	
	root 'welcome#index'

	get 'user_root' => 'welcome#admin'


	resources :movies, :auditoriums, :orders, :showtimes

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_action :user_admin, except: [:index]

	layout :resolve_layout

	def index
		@movies = Movie.where(now_playing: true)
		@days = []
		day = Date.today
		7.times do
			movies = {}
			showtimes = Showtime.where(date: day.to_s )
			showtimes.each do |showtime|
				if !movies[showtime.movie.title]
					movies[showtime.movie.title] = []
				end
				movies[showtime.movie.title] << [showtime.time, (showtime.auditorium.capacity - Order.where(showtime: showtime).count)]
			end
			@days << movies
			day += 1
		end
	end

	def admin
		@auditoriums = Auditorium.all
		@movies = Movie.all
		@showtimes = Showtime.all
		@orders = Order.all
	end

	private

	def resolve_layout
	    case action_name
	    	when "index"
	    		"root"
			when "admin"
	        	"admin"
	    	else
	        	"theatr"
	    end
	end 
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/admin.html.erb
<h1>Admin Panel</h1>

<div id="admin_panel movies">
	<h2>Movies</h2>
	<table>
		<thead>
			<tr>
				<th></th>
				<th>ID</th>
				<th>Title</th>
				<th>Length</th>
				<th>Rating</th>
				<th>Now Playing</th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @movies.each do |movie| %>
				<tr>
					<td><!-- movie poster goes here --></td>
					<td><%= movie.id %></td>
					<td><%= movie.title %></td>
					<td><%= movie.length %></td>
					<td><%= movie.rating %></td>
					<td><%= movie.now_playing %></td>
					<td><%= link_to 'Add Showtimes', new_showtime_path(:movie => movie.id) %></td>
					<td><%= link_to 'Edit', edit_movie_path(movie) %></td>
					<td><%= link_to 'Delete', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				</tr>
			<% end %>
		</tbody>
	</table>

	<%= link_to 'New', new_movie_path %>
</div>

<div id="admin_panel auditoriums">
	<h2>Auditoriums</h2>
	<table>
		<thead>
			<tr>
				<th>ID</th>
				<th>Name</th>
				<th>Capacity</th>
				<th>Now Playing</th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @auditoriums.each do |auditorium| %>
				<tr>
					<td><%= auditorium.id %></td>
					<td><%= auditorium.name %></td>
					<td><%= auditorium.capacity %></td>
					<td>
						<div>
	  						<% show = Showtime.where(auditorium: auditorium, date: Date.today) %>
	  						<%= !show.empty? ? show[0].movie.title : "No Showtimes" %>
						</div>
					</td>
					<td><%= link_to 'Add Showtimes', new_showtime_path(:auditorium => auditorium.id) %></td>
					<td><%= link_to 'Edit', edit_auditorium_path(auditorium) %></td>
					<td><%= link_to 'Delete', auditorium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				</tr>
			<% end %>
		</tbody>
	</table>

	<%= link_to 'New', new_auditorium_path %>
</div>

<div id="admin_panel orders">
	<h2>Orders</h2>
	<table>
		<thead>
			<tr>
				<th>Movie</th>
				<th>Date</th>
				<th>Time</th>
				<th>Email</th>
				<th>Price</th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @orders.each do |order| %>
				<tr>
					<td><%= order.showtime.movie.title %></td>
					<td><%= order.showtime.date %></td>
					<td><%= order.showtime.time %></td>
					<td><%= order.email %></td>
					<td><%= order.price %></td>
					<td><%= link_to 'Edit', edit_order_path(order) %></td>
					<td><%= link_to 'Delete', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<br><br>
	<h2>Orders By Movie</h2>
	<%= select_tag(:movie_id, options_for_select(@movies.map{|m|[m.title, ("movie_" + m.id.to_s)]})) %>
	<% @movies.each do |movie| %>
		<div id=<%= ("movie_" + movie.id.to_s) %> class="orders_by_movie hidden">
			<table>
				<thead>
					<tr>
						<th>Date</th>
						<th>Time</th>
						<th>Email</th>
						<th>Price</th>
					</tr>
				</thead>
				<tbody>
					<% movie.orders.each do |order| %>
						<tr>
							<td><%= order.showtime.date %></td>
							<td><%= order.showtime.time %></td>
							<td><%= order.email %></td>
							<td><%= order.price %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	<% end %>
</div>

<div id="admin_panel showtimes">
	<h2>Showtimes</h2>
	<table>
		<thead>
			<tr>
				<th>ID</th>
				<th>Auditorium</th>
				<th>Movie</th>
				<th>Date</th>
				<th>Time</th>
				<th>Seats Remaining</th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @showtimes.each do |showtime| %>
				<tr>
					<td><%= showtime.id %></td>
					<td><%= showtime.auditorium.name %></td>
					<td><%= showtime.movie.title %></td>
					<td><%= showtime.date %></td>
					<td><%= showtime.time %></td>
					<td><%= showtime.auditorium.capacity - Order.where(showtime_id: showtime.id).count %></td>
					<td><%= link_to 'Edit', edit_showtime_path(showtime) %></td>
					<td><%= link_to 'Delete', showtime, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				</tr>
			<% end %>
		</tbody>
	</table>

	<%= link_to 'New', new_showtime_path %>
</div>

app/views/welcome/index.html.erb
<div class="owl-carousel" id="home_carousel">
	<% @movies.each do |movie| %><div class="movie_poster">
		<div class="poster_description">
			<div class="playing description_field">
				Now Playing
			</div>
			<div class="movie_title description_field">
				<%= link_to movie.title, movie_path(movie), :class => "movie_title" %>
			</div>
			<%= link_to(movie_path(movie)) do %>
				<div class="buy_tickets description_field">
					<button class="get_tickets">Get Tickets</button>
				</div>
			<% end %>
		</div>
		<%= link_to(movie) do %>
			<%= image_tag(movie.poster, :class => "poster_image grow") %>
		<% end %>
	</div>
	<% end %>
</div>

<div id="gallery">
	<div id="now_playing_header">
		<span>Now Playing</span>
	</div>
	<div id="now_playing_content">
		<% 7.times do |int| %><a href="#" id='day_<%= int %>' class="np_nav_button"><%= int == 0 ? "<div class='np_date_select selected'>".html_safe : "<div class='np_date_select'>".html_safe %><div class="weekday"><%= int == 0 ? "Today".html_safe : (Date.today + int).strftime('%a') %></div><div class="month"><%= (Date.today + int).strftime('%b') %></div><div class="day"><%= (Date.today + int).day %></div></div></a><% end %>

		<% today = Date.today %>
		<% @days.each do |day| %>
			<%= today == Date.today ? '<div class="showing_day">'.html_safe : '<div class="showing_day hidden">'.html_safe %>
				<% if day.empty? %>
					There are no showtimes for this day.
				<% else %>
					<% day.each do |movie, showtimes| %>
						<div class="movie_showtimes">
							<div class="np_movie_title">
							<%= link_to movie, movie_path(Movie.where(title: movie)[0].id) %>
							</div>
							<div class="np_movie_showtimes"> 
							<% showtimes.each do |showtime| %>
								<div class="each_showtime">							
									<% if showtime[1] > 0 %>
										<%= link_to showtime[0].strftime("%-I:%M%p"), new_order_path(:showtime =>Showtime.where(movie: Movie.where(title: movie), time: showtime[0], date: today)[0] ) %>  
									<% else %>
										<text class="sold_out"><%= showtime[0].strftime("%-I:%M%p") %></text>
									<% end %> 
								</div>
							<% end %>
							</div>
						</div>
					<% end %>
				<% end %>
			</div>
			<% today += 1 %>
		<% end %>
	</div>
</div> 